
import { Category, WordItem } from './types';

const createItems = (list: [string, string][]): WordItem[] => {
  return list.map(([target, hint]) => ({ target, hint }));
};

export const CATEGORIES: Category[] = [
  {
    id: 'footballers',
    name: 'Futbolistas',
    isLocked: true,
    items: createItems([
      ['Lionel Messi', 'Argentina'],
      ['Cristiano Ronaldo', 'Portugal'],
      ['Kylian Mbappé', 'Francia'],
      ['Erling Haaland', 'Noruega'],
      ['Jude Bellingham', 'Inglaterra'],
      ['Vinícius Júnior', 'Brasil'],
      ['Mohamed Salah', 'Egipto'],
      ['Kevin De Bruyne', 'Bélgica'],
      ['Robert Lewandowski', 'Polonia'],
      ['Neymar Jr.', 'Brasil'],
      ['Bukayo Saka', 'Inglaterra'],
      ['Harry Kane', 'Inglaterra'],
      ['Rodri', 'España'],
      ['Bruno Fernandes', 'Portugal'],
      ['Khvicha Kvaratskhelia', 'Georgia'],
      ['Federico Chiesa', 'Italia'],
      ['Victor Osimhen', 'Nigeria'],
      ['Bernardo Silva', 'Portugal'],
      ['Antoine Griezmann', 'Francia'],
      ['Lautaro Martínez', 'Argentina'],
      ['Thibaut Courtois', 'Bélgica'],
      ['Alisson Becker', 'Brasil'],
      ['Gianluigi Donnarumma', 'Italia'],
      ['Achraf Hakimi', 'Marruecos'],
      ['Trent Alexander-Arnold', 'Inglaterra'],
      ['Jules Koundé', 'Francia'],
      ['Virgil van Dijk', 'Países Bajos'],
      ['William Saliba', 'Francia'],
      ['Antonio Rüdiger', 'Alemania'],
      ['Pedri', 'España'],
      ['Declan Rice', 'Inglaterra'],
      ['Fede Valverde', 'Uruguay'],
      ['Jamal Musiala', 'Alemania'],
      ['Florian Wirtz', 'Alemania'],
      ['Marcus Rashford', 'Inglaterra'],
      ['Raphinha', 'Brasil'],
      ['Joshua Kimmich', 'Alemania'],
      ['Rodrigo De Paul', 'Argentina'],
      ['Alexis Mac Allister', 'Argentina'],
      ['Emiliano Martínez', 'Argentina'],
      ['Luis Díaz', 'Colombia'],
      ['Federico Valverde', 'Uruguay'],
      ['Cole Palmer', 'Inglaterra'],
      ['Lamine Yamal', 'España'],
      ['Raphaël Varane', 'Francia'],
      ['João Cancelo', 'Portugal'],
      ['Ferran Torres', 'España'],
      ['Mason Mount', 'Inglaterra'],
      ['Phil Foden', 'Inglaterra'],
      ['Kai Havertz', 'Alemania'],
      ['Marco Reus', 'Alemania'],
      ['Paulo Dybala', 'Argentina'],
      ['Thomas Müller', 'Alemania'],
      ['Antoine Semenyo', 'Ghana'],
      ['Matheus Cunha', 'Brasil'],
      ['Callum Wilson', 'Inglaterra'],
      ['Nicolas Jackson', 'Senegal'],
      ['João Félix', 'Portugal'],
      ['Sofyan Amrabat', 'Marruecos'],
      ['Hirving Lozano', 'México'],
      ['Eduardo Camavinga', 'Francia'],
      ['Jorginho', 'Italia'],
      ['Serge Gnabry', 'Alemania'],
      ['Kingsley Coman', 'Francia'],
      ['Riyad Mahrez', 'Argelia'],
      ['Ilkay Gündogan', 'Alemania'],
      ['Mateo Kovacic', 'Croacia'],
      ['Lucas Paquetá', 'Brasil'],
      ['Leon Goretzka', 'Alemania'],
      ['Rodrigo Bentancur', 'Uruguay'],
      ['Marquinhos', 'Brasil'],
      ['Presnel Kimpembe', 'Francia'],
      ['David Alaba', 'Austria'],
      ['Raphaël Guerreiro', 'Portugal'],
      ['Theo Hernández', 'Francia'],
      ['Alphonso Davies', 'Canadá'],
      ['Achraf Dari', 'Marruecos'],
      ['Ederson Moraes', 'Brasil'],
      ['Mike Maignan', 'Francia'],
      ['André Onana', 'Camerún'],
      ['Yann Sommer', 'Suiza'],
      ['Alex Meret', 'Italia'],
      ['Dani Olmo', 'España'],
      ['Papu Gómez', 'Argentina'],
      ['Lucas Ocampos', 'Argentina'],
      ['Wilfried Zaha', 'Costa de Marfil'],
      ['Josko Gvardiol', 'Croacia'],
      ['Milan Škriniar', 'Eslovaquia'],
      ['Kalvin Phillips', 'Inglaterra'],
      ['James Maddison', 'Inglaterra'],
      ['Trevoh Chalobah', 'Inglaterra'],
      ['Leandro Paredes', 'Argentina'],
      ['Bryan Cristante', 'Italia'],
      ['Nicolò Barella', 'Italia'],
      ['Giovani Lo Celso', 'Argentina'],
      ['Hugo Lloris', 'Francia'],
      ['Kepa Arrizabalaga', 'España'],
      ['Aaron Ramsdale', 'Inglaterra'],
      ['Jordan Pickford', 'Inglaterra']
    ])
  },
  {
    id: 'singers',
    name: 'Cantantes',
    items: createItems([
      ['Shakira', 'Barranquilla'],
      ['Karol G', 'La Bichota'],
      ['J Balvin', 'Colores'],
      ['Maluma', 'Hawái'],
      ['Feid', 'Ferxxo'],
      ['Sebastián Yatra', 'Tacones Rojos'],
      ['Camilo', 'Bigote'],
      ['Manuel Turizo', 'La Bachata'],
      ['Carlos Vives', 'Vallenato'],
      ['Juanes', 'Camisa Negra'],
      ['Bad Bunny', 'Conejo Malo'],
      ['Daddy Yankee', 'Gasolina'],
      ['Ozuna', 'Ojos Claros'],
      ['Anuel AA', 'Real Hasta la Muerte'],
      ['Rauw Alejandro', 'Saturno'],
      ['Rosalía', 'Motomami'],
      ['Enrique Iglesias', 'Héroe'],
      ['Quevedo', 'Quédate'],
      ['Peso Pluma', 'Corridos Tumbados'],
      ['Thalía', 'Amor a la Mexicana'],
      ['Romeo Santos', 'Rey de la Bachata'],
      ['Juan Luis Guerra', 'Burbujas de Amor'],
      ['Ricky Martin', 'Livin la Vida Loca'],
      ['Chayanne', 'Torero'],
      ['Marc Anthony', 'Vivir mi Vida'],
      ['Jennifer López', 'El Anillo'],
      ['Becky G', 'Mayores'],
      ['Tini', 'Triple T'],
      ['Duki', 'Modo Diablo'],
      ['Bizarrap', 'Sessions'],
      ['Trueno', 'Mate'],
      ['Morat', 'Besos en Guerra'],
      ['Piso 21', 'Déjala que Vuelva'],
      ['Fonseca', 'Te Mando Flores'],
      ['Andrés Cepeda', 'Día Tras Día'],
      ['Pipe Bueno', 'Cupido Falló'],
      ['Beele', 'Loco'],
      ['Ryan Castro', 'Mujeriego'],
      ['Blessd', 'Medallo'],
      ['Pirlo', '420'],
      ['Anuel', 'Brrr']
    ])
  },
  {
    id: 'celebrities',
    name: 'Famosos',
    items: createItems([
      ['Taylor Swift', 'Eras Tour'],
      ['Beyoncé', 'Queen B'],
      ['Kim Kardashian', 'Reality'],
      ['Lionel Messi', 'Campeón del Mundo'],
      ['Cristiano Ronaldo', 'CR7'],
      ['Bad Bunny', 'Conejo Malo'],
      ['Dwayne “The Rock” Johnson', 'Lucha Libre'],
      ['Zendaya', 'Euphoria'],
      ['Kylie Jenner', 'Cosméticos'],
      ['Drake', 'Canadá'],
      ['Billie Eilish', 'Pelo de colores'],
      ['Shakira', 'Waka Waka'],
      ['Rihanna', 'Paraguas'],
      ['Tom Holland', 'Spider-Man'],
      ['LeBron James', 'King James'],
      ['Selena Gomez', 'Disney'],
      ['Jennifer Lopez', 'JLo'],
      ['Ariana Grande', 'Coleta Alta'],
      ['Neymar Jr.', 'Caídas'],
      ['Chris Hemsworth', 'Thor'],
      ['Robert Downey Jr.', 'Iron Man'],
      ['Keanu Reeves', 'Matrix'],
      ['Margot Robbie', 'Barbie'],
      ['Oprah Winfrey', 'Entrevista'],
      ['Will Smith', 'Príncipe de Bel-Air'],
      ['Justin Bieber', 'Baby'],
      ['Katy Perry', 'Fuegos Artificiales'],
      ['Ed Sheeran', 'Guitarra'],
      ['Jason Momoa', 'Aquaman'],
      ['Lady Gaga', 'Poker Face'],
      ['Johnny Depp', 'Pirata'],
      ['Eminem', 'Rap God'],
      ['Post Malone', 'Tatuajes'],
      ['Dua Lipa', 'Levitating'],
      ['Ryan Reynolds', 'Deadpool'],
      ['Adam Sandler', 'Comedia'],
      ['Timothée Chalamet', 'Wonka'],
      ['Cardi B', 'WAP'],
      ['Morgan Freeman', 'Voz de Dios']
    ])
  },
  {
    id: 'drinks',
    name: 'Tragos',
    isLocked: true,
    items: createItems([
      ['Jack Daniel’s', 'Whiskey'],
      ['Johnnie Walker', 'Caminante'],
      ['Chivas Regal', 'Whiskey'],
      ['Old Parr', 'Abuelo'],
      ['Buchanan’s', 'Whiskey'],
      ['Glenfiddich', 'Single Malt'],
      ['The Macallan', 'Lujo'],
      ['Corona', 'Limón'],
      ['Heineken', 'Verde'],
      ['Budweiser', 'Americana'],
      ['Stella Artois', 'Copa'],
      ['Águila', 'Cerveza'],
      ['Club Colombia', 'Dorada'],
      ['Poker', 'Amigos'],
      ['Miller Lite', 'Ligera'],
      ['Costeña', 'Cerveza'],
      ['Smirnoff de lulo', 'Lulo'],
      ['Costeñita', 'Pequeña'],
      ['Ron Medellín', 'Antioquia'],
      ['Sello Rojo', 'Whiskey'],
      ['Ron Viejo de Caldas', 'Caldas'],
      ['Bacardí', 'Murciélago'],
      ['Sello Azul', 'Blue'],
      ['Four Loko', 'Descontrol'],
      ['Perro con perro', 'Bajón'],
      ['Like', 'Burbujas']
    ])
  },
  {
    id: 'professors',
    name: 'Profesores',
    isLocked: true,
    items: createItems([
      ['Gabriel', 'Docente'],
      ['Rocha', 'Docente'],
      ['Pedro', 'Docente'],
      ['Winton', 'Docente'],
      ['Nelson', 'Docente'],
      ['Chacuto', 'Docente'],
      ['Bustamante', 'Docente'],
      ['Guty', 'Docente'],
      ['Alicia', 'Docente'],
      ['Daniel', 'Docente'],
      ['Javier', 'Docente'],
      ['Eugenio', 'Docente'],
      ['Riquett', 'Docente'],
      ['Críspulo', 'Docente'],
      ['Gilma', 'Docente'],
      ['Enrique', 'Docente'],
      ['Edwin', 'Docente'],
      ['Gerardo', 'Docente'],
      ['Rick', 'Docente'],
      ['Néstor', 'Docente'],
      ['Campuzano', 'Docente'],
      ['Zárate', 'Docente'],
      ['Ricardito', 'Docente'],
      ['Jorge', 'Docente'],
      ['Edwan', 'Docente'],
      ['Carpintero', 'Docente'],
      ['Freddy', 'Docente']
    ])
  },
  {
    id: 'sports',
    name: 'Deportes',
    items: createItems([
      ['Fútbol', 'Hinchada'],
      ['Baloncesto', 'Altura'],
      ['Tenis', 'Wimbledon'],
      ['Natación', 'Cloro'],
      ['Boxeo', 'Round'],
      ['Ciclismo', 'Cadena'],
      ['Voleibol', 'Bloqueo'],
      ['Béisbol', 'Home'],
      ['Fórmula 1', 'Pits'],
      ['Golf', 'Handicap'],
      ['Rugby', 'Tackle'],
      ['Atletismo', 'Meta']
    ])
  },
  {
    id: 'daily_life',
    name: 'Vida Cotidiana',
    items: createItems([
      ['Cama', 'Siesta'],
      ['Ducha', 'Vapor'],
      ['Celular', 'Cobertura'],
      ['Llaves', 'Llavero'],
      ['Billetera', 'Tarjeta'],
      ['Computador', 'Mouse'],
      ['Zapatos', 'Cordones'],
      ['Reloj', 'Tic-tac'],
      ['Gafas', 'Aumento'],
      ['Silla', 'Respaldo'],
      ['Cepillo de dientes', 'Caries'],
      ['Televisor', 'Control']
    ])
  },
  {
    id: 'food',
    name: 'Comidas',
    items: createItems([
      ['Pizza', 'Pepperoni'],
      ['Hamburguesa', 'Chatarra'],
      ['Sushi', 'Palillos'],
      ['Sopa', 'Cuchara'],
      ['Helado', 'Derretido'],
      ['Ensalada', 'Dieta'],
      ['Pollo Frito', 'Alas'],
      ['Pasta', 'Harina'],
      ['Tacos', 'México'],
      ['Huevo', 'Yema'],
      ['Pan', 'Miga'],
      ['Fruta', 'Semilla']
    ])
  },
  {
    id: 'places',
    name: 'Lugares',
    items: createItems([
      ['Playa', 'Bronceador'],
      ['Montaña', 'Nieve'],
      ['Colegio', 'Recreo'],
      ['Hospital', 'Camilla'],
      ['Cine', 'Cartelera'],
      ['Discoteca', 'Dj'],
      ['Aeropuerto', 'Pasaporte'],
      ['Restaurante', 'Chef'],
      ['Gimnasio', 'Rutina'],
      ['Parque', 'Columpio'],
      ['Centro Comercial', 'Vitrina'],
      ['Estadio', 'Grada']
    ])
  },
  {
    id: 'objects',
    name: 'Objetos',
    items: createItems([
      ['Martillo', 'Clavo'],
      ['Guitarra', 'Cuerda'],
      ['Lápiz', 'Grafito'],
      ['Cuchillo', 'Filo'],
      ['Botella', 'Corcho'],
      ['Libro', 'Página'],
      ['Mesa', 'Mantel'],
      ['Cámara', 'Flash'],
      ['Maleta', 'Equipaje'],
      ['Espejo', 'Reflejo']
    ])
  },
  {
    id: 'animals',
    name: 'Animales',
    items: createItems([
      ['Perro', 'Huella'],
      ['Gato', 'Tejado'],
      ['León', 'Sabana'],
      ['Elefante', 'Marfil'],
      ['Pájaro', 'Nido'],
      ['Pez', 'Anzuelo'],
      ['Serpiente', 'Veneno'],
      ['Vaca', 'Mugido'],
      ['Caballo', 'Establo'],
      ['Mono', 'Liana']
    ])
  },
  {
    id: 'professions',
    name: 'Profesiones',
    items: createItems([
      ['Doctor', 'Bata'],
      ['Policía', 'Placa'],
      ['Profesor', 'Tiza'],
      ['Bombero', 'Sirena'],
      ['Chef', 'Gorro'],
      ['Piloto', 'Cabina'],
      ['Astronauta', 'Gravedad'],
      ['Cantante', 'Micrófono'],
      ['Pintor', 'Pincel'],
      ['Mecánico', 'Tuerca']
    ])
  }
];